"""
PIO-based IR Transmitter for LifeSize Camera

Uses a single PIO state machine to generate 38kHz carrier with
mark/space timing control. The PIO program rapidly toggles the
output pin during mark periods to create the carrier, and holds
low during space periods.

Clock divider is calculated to achieve accurate 38kHz carrier
frequency with ~33% duty cycle.
"""

import rp2
from rp2 import PIO, StateMachine, asm_pio
from machine import Pin
import time

from config import (
    PIN_IR_LED,
    IR_CARRIER_FREQ_HZ,
    IR_CARRIER_DUTY_CYCLE,
    DEBUG_IR,
    DEBUG_TIMING,
    IRCommand,
)
from ir_protocol import protocol


# =============================================================================
# PIO Programs
# =============================================================================

@asm_pio(set_init=PIO.OUT_LOW)
def ir_simple():
    """
    Simple IR transmitter - receives pulse train and outputs directly.

    Input format: alternating mark/space durations as cycle counts.
    Uses a simple on/off approach - carrier is generated by rapid toggling.

    For 38kHz carrier at 125MHz clock:
    - Period = 3289 cycles
    - High time (33%) = ~1096 cycles
    - Low time (67%) = ~2193 cycles

    We'll use a fixed carrier cycle and count how many to do per mark.
    """
    wrap_target()

    # Pull mark duration (in carrier cycles)
    pull(block)
    mov(x, osr)

    # If X is 0, skip to space
    jmp(not_x, "do_space")

    # Generate carrier for mark duration
    label("carrier_loop")
    set(pins, 1)                [12]    # 13 cycles high
    set(pins, 0)                [12]    # 13 cycles low
    jmp(x_dec, "carrier_loop")          # 1 cycle (total 27 per carrier cycle)

    label("do_space")
    # Pull space duration
    pull(block)
    mov(x, osr)

    # If X is 0, skip delay
    jmp(not_x, "done_space")

    # Delay for space (output stays low)
    label("space_delay")
    nop()                       [24]    # 25 cycles
    jmp(x_dec, "space_delay")           # 1 cycle (total 26 per iteration)

    label("done_space")
    wrap()


# =============================================================================
# IR Transmitter Class
# =============================================================================

class IRTransmitter:
    """
    High-level IR transmitter using PIO for precise timing.

    Converts protocol timings to PIO cycle counts and manages transmission.
    """

    def __init__(self, pin_num=PIN_IR_LED, pio_num=0, sm_num=0):
        """
        Initialize the IR transmitter.

        Args:
            pin_num: GPIO pin number for IR LED
            pio_num: PIO block number (0 or 1)
            sm_num: State machine number (0-3)
        """
        self.pin_num = pin_num
        self.pin = Pin(pin_num, Pin.OUT, value=0)
        self.pio_num = pio_num
        self.sm_num = sm_num
        self.sm = None
        self.is_transmitting = False

        # Calculate timing constants
        # System clock is 125MHz on Pico 2W (150MHz on RP2350, but MicroPython defaults to 125)
        self.sys_clock = 125_000_000

        # PIO carrier loop timing:
        # - set(pins, 1) [12] = 13 cycles high
        # - set(pins, 0) [12] = 13 cycles low
        # - jmp = 1 cycle
        # Total = 27 PIO cycles per carrier period
        self.carrier_loop_cycles = 27

        # PIO space loop timing:
        # - nop [24] = 25 cycles
        # - jmp = 1 cycle
        # Total = 26 PIO cycles per space iteration
        self.space_loop_cycles = 26

        # Calculate clock divider for 38kHz carrier
        # PIO clock = carrier_freq * cycles_per_carrier_period
        # Divider = sys_clock / PIO_clock
        self.pio_divider = self.sys_clock / (IR_CARRIER_FREQ_HZ * self.carrier_loop_cycles)

        # Calculate microseconds per loop iteration at the PIO clock rate
        pio_clock = self.sys_clock / self.pio_divider
        self.us_per_carrier_cycle = (self.carrier_loop_cycles / pio_clock) * 1_000_000
        self.us_per_space_cycle = (self.space_loop_cycles / pio_clock) * 1_000_000

        self._init_pio()

    def _init_pio(self):
        """Initialize the PIO state machine."""
        try:
            # Remove any existing program
            if self.sm is not None:
                self.sm.active(0)

            # Create state machine with the simple IR program
            self.sm = StateMachine(
                self.sm_num,
                ir_simple,
                freq=int(self.sys_clock / self.pio_divider),
                set_base=self.pin,
            )

            if DEBUG_IR:
                actual_freq = self.sys_clock / self.pio_divider
                print(f"IR TX: PIO SM{self.sm_num} initialized")
                print(f"  Clock divider: {self.pio_divider:.2f}")
                print(f"  PIO frequency: {actual_freq/1e6:.2f} MHz")
                print(f"  Carrier target: {IR_CARRIER_FREQ_HZ/1000:.1f} kHz")

        except Exception as e:
            print(f"IR TX: Failed to initialize PIO: {e}")
            raise

    def _us_to_cycles(self, microseconds: int) -> int:
        """
        Convert microseconds to carrier cycle counts.

        Each carrier cycle takes self.us_per_carrier_cycle microseconds.
        For 38kHz with 27-cycle loop at 1.026MHz, this is ~26.3us.
        """
        carrier_cycles = microseconds / self.us_per_carrier_cycle
        return max(1, int(carrier_cycles))

    def _us_to_space_cycles(self, microseconds: int) -> int:
        """
        Convert microseconds to space delay cycle counts.

        Each space iteration takes self.us_per_space_cycle microseconds.
        For 26-cycle loop at 1.026MHz, this is ~25.3us.
        """
        if microseconds == 0:
            return 0
        space_cycles = microseconds / self.us_per_space_cycle
        return max(1, int(space_cycles))

    def transmit_command(self, command_code: int):
        """
        Transmit a single IR command.

        Args:
            command_code: 8-bit LifeSize command code
        """
        if DEBUG_IR:
            print(f"IR TX: Sending command 0x{command_code:02X}")

        start_time = time.ticks_us()

        # Get the timing sequence
        timings = protocol.encode_command(command_code)

        # Convert to PIO cycle counts
        pulse_data = []
        for mark_us, space_us in timings:
            mark_cycles = self._us_to_cycles(mark_us)
            space_cycles = self._us_to_space_cycles(space_us)
            pulse_data.append(mark_cycles)
            pulse_data.append(space_cycles)

        # Start the state machine
        self.sm.active(1)
        self.is_transmitting = True

        # Feed pulse data to PIO FIFO
        try:
            for cycles in pulse_data:
                self.sm.put(cycles)

            # Wait for transmission to complete
            # Estimate total time and add margin
            total_us = protocol.calculate_frame_duration(command_code)
            time.sleep_us(total_us + 1000)  # Add 1ms margin

        finally:
            self.sm.active(0)
            self.is_transmitting = False
            self.pin.value(0)  # Ensure LED is off

        if DEBUG_TIMING:
            elapsed = time.ticks_diff(time.ticks_us(), start_time)
            print(f"IR TX: Frame took {elapsed}us (expected ~{total_us}us)")

    def transmit_raw_pulses(self, pulse_train: list):
        """
        Transmit a raw pulse train (for testing/debugging).

        Args:
            pulse_train: List of alternating mark/space values in microseconds
        """
        if DEBUG_IR:
            print(f"IR TX: Sending raw pulse train ({len(pulse_train)} elements)")

        # Convert to cycles
        cycle_data = []
        for i, us in enumerate(pulse_train):
            if i % 2 == 0:  # Mark
                cycle_data.append(self._us_to_cycles(us))
            else:  # Space
                cycle_data.append(self._us_to_space_cycles(us))

        # Ensure even number of elements (mark/space pairs)
        if len(cycle_data) % 2 == 1:
            cycle_data.append(0)  # Add zero space at end

        # Start transmission
        self.sm.active(1)
        self.is_transmitting = True

        try:
            for cycles in cycle_data:
                self.sm.put(cycles)

            # Wait for completion
            total_us = sum(pulse_train)
            time.sleep_us(total_us + 1000)

        finally:
            self.sm.active(0)
            self.is_transmitting = False
            self.pin.value(0)

    def test_carrier(self, duration_ms: int = 100):
        """
        Test the carrier generation by outputting continuous carrier.

        Args:
            duration_ms: Duration in milliseconds
        """
        print(f"IR TX: Testing carrier for {duration_ms}ms")

        # Calculate cycles for continuous carrier
        carrier_cycles = self._us_to_cycles(duration_ms * 1000)

        self.sm.active(1)
        self.sm.put(carrier_cycles)  # Mark
        self.sm.put(0)  # No space

        time.sleep_ms(duration_ms + 10)

        self.sm.active(0)
        self.pin.value(0)
        print("IR TX: Carrier test complete")

    def test_command(self, command_code: int, repeats: int = 1, gap_ms: int = 57):
        """
        Test transmitting a command with repeats.

        Args:
            command_code: Command to send
            repeats: Number of times to repeat
            gap_ms: Gap between repeats in milliseconds
        """
        cmd_name = None
        for name in dir(IRCommand):
            if not name.startswith('_') and getattr(IRCommand, name) == command_code:
                cmd_name = name
                break

        print(f"IR TX: Testing {cmd_name or hex(command_code)} x{repeats}")

        for i in range(repeats):
            self.transmit_command(command_code)
            if i < repeats - 1:
                time.sleep_ms(gap_ms)

        print(f"IR TX: Test complete")


# =============================================================================
# Software-based IR Transmitter (Fallback)
# =============================================================================

class IRTransmitterSoftware:
    """
    Software-based IR transmitter using bit-banging.

    Less precise than PIO but works as a fallback.
    Uses tight timing loops for carrier generation.
    """

    def __init__(self, pin_num=PIN_IR_LED):
        self.pin = Pin(pin_num, Pin.OUT, value=0)
        self.carrier_half_period_us = 13  # ~38kHz (26us period)

    def _carrier_burst(self, duration_us: int):
        """Generate a carrier burst for the specified duration."""
        cycles = duration_us // 26
        for _ in range(cycles):
            self.pin.value(1)
            time.sleep_us(self.carrier_half_period_us)
            self.pin.value(0)
            time.sleep_us(self.carrier_half_period_us)

    def _space(self, duration_us: int):
        """Wait with IR LED off."""
        self.pin.value(0)
        time.sleep_us(duration_us)

    def transmit_command(self, command_code: int):
        """Transmit a command using software timing."""
        timings = protocol.encode_command(command_code)

        for mark_us, space_us in timings:
            self._carrier_burst(mark_us)
            if space_us > 0:
                self._space(space_us)

        self.pin.value(0)


# =============================================================================
# Module-level transmitter instance
# =============================================================================

# Create default transmitter
_transmitter = None


def get_transmitter(use_pio: bool = True) -> IRTransmitter:
    """Get or create the default IR transmitter instance."""
    global _transmitter
    if _transmitter is None:
        if use_pio:
            try:
                _transmitter = IRTransmitter()
            except Exception as e:
                print(f"PIO init failed, using software: {e}")
                _transmitter = IRTransmitterSoftware()
        else:
            _transmitter = IRTransmitterSoftware()
    return _transmitter


def send_command(command_code: int):
    """Convenience function to send a single command."""
    tx = get_transmitter()
    tx.transmit_command(command_code)


# =============================================================================
# Test code
# =============================================================================

if __name__ == "__main__":
    print("IR Transmitter Test")
    print("=" * 50)

    # Create transmitter
    tx = IRTransmitter()

    print("\nPress Ctrl+C to stop\n")

    # Test each command
    commands = [
        ("UP", IRCommand.UP),
        ("DOWN", IRCommand.DOWN),
        ("LEFT", IRCommand.LEFT),
        ("RIGHT", IRCommand.RIGHT),
        ("ZOOM_IN", IRCommand.ZOOM_IN),
        ("ZOOM_OUT", IRCommand.ZOOM_OUT),
    ]

    try:
        for name, cmd in commands:
            print(f"\nSending {name}...")
            tx.test_command(cmd, repeats=3, gap_ms=57)
            time.sleep(1)

    except KeyboardInterrupt:
        print("\nTest stopped")

    print("\nTest complete")
