"""
PIO-based IR Transmitter for LifeSize Camera

Uses two PIO state machines:
- SM0: Generates 38kHz carrier signal (26.3us period, 33% duty)
- SM1: Controls mark/space timing with microsecond precision

The carrier SM runs continuously when enabled, and the timing SM
gates the carrier on/off to create the modulated IR signal.
"""

import rp2
from rp2 import PIO, StateMachine, asm_pio
from machine import Pin
import time
import array

from config import (
    PIN_IR_LED,
    IR_CARRIER_FREQ_HZ,
    IR_CARRIER_DUTY_CYCLE,
    DEBUG_IR,
    DEBUG_TIMING,
)
from ir_protocol import protocol, IRCommand


# =============================================================================
# PIO Programs
# =============================================================================

@asm_pio(set_init=PIO.OUT_LOW, sideset_init=PIO.OUT_LOW)
def ir_carrier():
    """
    PIO program for 38kHz carrier generation with gating.

    The carrier runs when the input pin (from timing SM) is high.
    Uses sideset for the actual IR output to achieve precise timing.

    At 125MHz system clock:
    - 38kHz = 3289 cycles per period
    - 33% duty = ~1096 cycles high, ~2193 cycles low

    We use autopull to read the timing values from FIFO.
    """
    # Wait for enable signal (pull from FIFO or wait on pin)
    wrap_target()

    # Pull timing value (number of carrier cycles for this burst)
    pull(block)                 # Get burst length from FIFO
    mov(x, osr)                 # Move to X for counting

    # Generate carrier bursts
    label("burst_loop")
    set(pins, 1)        .side(1)  [10]   # IR LED on (adjust delay for duty)
    nop()                       [10]
    nop()                       [10]
    set(pins, 0)        .side(0)  [20]   # IR LED off
    nop()                       [20]
    nop()                       [20]
    jmp(x_dec, "burst_loop")    [5]      # Continue burst

    wrap()


@asm_pio(out_init=PIO.OUT_LOW, set_init=PIO.OUT_LOW)
def ir_modulator():
    """
    Simplified PIO program that directly modulates IR output.

    Reads mark/space timing values from FIFO:
    - Mark: Output carrier signal for specified duration
    - Space: Output low for specified duration

    Each FIFO entry contains delay cycles (prescaled externally).
    Even entries = mark duration, odd entries = space duration.
    """
    wrap_target()

    # Get mark duration
    pull(block)
    mov(x, osr)

    # Mark period - toggle rapidly to create carrier
    label("mark_loop")
    set(pins, 1)                [7]     # High for ~8 cycles
    set(pins, 0)                [15]    # Low for ~16 cycles (33% duty)
    jmp(x_dec, "mark_loop")

    # Get space duration
    pull(block)
    mov(x, osr)

    # Space period - just wait with output low
    label("space_loop")
    nop()                       [23]    # Delay loop (~24 cycles)
    jmp(x_dec, "space_loop")

    wrap()


@asm_pio(set_init=PIO.OUT_LOW)
def ir_simple():
    """
    Simple IR transmitter - receives pulse train and outputs directly.

    Input format: alternating mark/space durations as cycle counts.
    Uses a simple on/off approach - carrier is generated by rapid toggling.

    For 38kHz carrier at 125MHz clock:
    - Period = 3289 cycles
    - High time (33%) = ~1096 cycles
    - Low time (67%) = ~2193 cycles

    We'll use a fixed carrier cycle and count how many to do per mark.
    """
    wrap_target()

    # Pull mark duration (in carrier cycles)
    pull(block)
    mov(x, osr)

    # If X is 0, skip to space
    jmp(not_x, "do_space")

    # Generate carrier for mark duration
    label("carrier_loop")
    set(pins, 1)                [12]    # ~13 cycles high
    set(pins, 0)                [12]    # ~13 cycles low (total ~26 for carrier)
    jmp(x_dec, "carrier_loop")

    label("do_space")
    # Pull space duration
    pull(block)
    mov(x, osr)

    # If X is 0, skip delay
    jmp(not_x, "done_space")

    # Delay for space (output stays low)
    label("space_delay")
    nop()                       [24]    # ~25 cycles per iteration
    jmp(x_dec, "space_delay")

    label("done_space")
    wrap()


# =============================================================================
# IR Transmitter Class
# =============================================================================

class IRTransmitter:
    """
    High-level IR transmitter using PIO for precise timing.

    Converts protocol timings to PIO cycle counts and manages transmission.
    """

    def __init__(self, pin_num=PIN_IR_LED, pio_num=0, sm_num=0):
        """
        Initialize the IR transmitter.

        Args:
            pin_num: GPIO pin number for IR LED
            pio_num: PIO block number (0 or 1)
            sm_num: State machine number (0-3)
        """
        self.pin_num = pin_num
        self.pin = Pin(pin_num, Pin.OUT, value=0)
        self.pio_num = pio_num
        self.sm_num = sm_num
        self.sm = None
        self.is_transmitting = False

        # Calculate timing constants
        # System clock is 125MHz on Pico 2W
        self.sys_clock = 125_000_000

        # For simple carrier generation at ~38kHz
        # Each carrier cycle = ~26us = ~3250 system cycles
        # Using divider of 1, we count carrier periods

        # Carrier period in system cycles (for 38kHz)
        self.carrier_period_cycles = self.sys_clock // IR_CARRIER_FREQ_HZ

        # We use ~26 cycles per carrier half-cycle in PIO (13 high + 13 low)
        # So actual carrier frequency = 125MHz / 26 = ~4.8MHz toggle rate
        # Which gives ~2.4MHz square wave - too fast!

        # Need to use clock divider. For 38kHz with 26-cycle loop:
        # divider = 125MHz / (38kHz * 26) = 125000000 / 988000 = ~126.5
        self.pio_divider = self.sys_clock / (IR_CARRIER_FREQ_HZ * 26)

        # Cycles per microsecond at the divided clock rate
        self.cycles_per_us = (self.sys_clock / self.pio_divider) / 1_000_000

        self._init_pio()

    def _init_pio(self):
        """Initialize the PIO state machine."""
        try:
            # Remove any existing program
            if self.sm is not None:
                self.sm.active(0)

            # Create state machine with the simple IR program
            self.sm = StateMachine(
                self.sm_num,
                ir_simple,
                freq=int(self.sys_clock / self.pio_divider),
                set_base=self.pin,
            )

            if DEBUG_IR:
                actual_freq = self.sys_clock / self.pio_divider
                print(f"IR TX: PIO SM{self.sm_num} initialized")
                print(f"  Clock divider: {self.pio_divider:.2f}")
                print(f"  PIO frequency: {actual_freq/1e6:.2f} MHz")
                print(f"  Carrier target: {IR_CARRIER_FREQ_HZ/1000:.1f} kHz")

        except Exception as e:
            print(f"IR TX: Failed to initialize PIO: {e}")
            raise

    def _us_to_cycles(self, microseconds: int) -> int:
        """
        Convert microseconds to PIO cycle counts.

        For the simple carrier generator, we count carrier periods.
        One carrier period = 26 PIO cycles = 1/38000 seconds = ~26.3us
        """
        # Each carrier cycle is ~26.3us, so:
        carrier_cycles = microseconds / 26.3
        return max(1, int(carrier_cycles))

    def _us_to_space_cycles(self, microseconds: int) -> int:
        """
        Convert microseconds to space delay cycles.

        Space loop is ~25 cycles per iteration at PIO clock rate.
        PIO clock = sys_clock / divider = ~987kHz
        Each iteration = 25/987000 seconds = ~25.3us
        """
        if microseconds == 0:
            return 0
        space_cycles = microseconds / 25.3
        return max(1, int(space_cycles))

    def transmit_command(self, command_code: int):
        """
        Transmit a single IR command.

        Args:
            command_code: 8-bit LifeSize command code
        """
        if DEBUG_IR:
            print(f"IR TX: Sending command 0x{command_code:02X}")

        start_time = time.ticks_us()

        # Get the timing sequence
        timings = protocol.encode_command(command_code)

        # Convert to PIO cycle counts
        pulse_data = []
        for mark_us, space_us in timings:
            mark_cycles = self._us_to_cycles(mark_us)
            space_cycles = self._us_to_space_cycles(space_us)
            pulse_data.append(mark_cycles)
            pulse_data.append(space_cycles)

        # Start the state machine
        self.sm.active(1)
        self.is_transmitting = True

        # Feed pulse data to PIO FIFO
        try:
            for cycles in pulse_data:
                self.sm.put(cycles)

            # Wait for transmission to complete
            # Estimate total time and add margin
            total_us = protocol.calculate_frame_duration(command_code)
            time.sleep_us(total_us + 1000)  # Add 1ms margin

        finally:
            self.sm.active(0)
            self.is_transmitting = False
            self.pin.value(0)  # Ensure LED is off

        if DEBUG_TIMING:
            elapsed = time.ticks_diff(time.ticks_us(), start_time)
            print(f"IR TX: Frame took {elapsed}us (expected ~{total_us}us)")

    def transmit_raw_pulses(self, pulse_train: list):
        """
        Transmit a raw pulse train (for testing/debugging).

        Args:
            pulse_train: List of alternating mark/space values in microseconds
        """
        if DEBUG_IR:
            print(f"IR TX: Sending raw pulse train ({len(pulse_train)} elements)")

        # Convert to cycles
        cycle_data = []
        for i, us in enumerate(pulse_train):
            if i % 2 == 0:  # Mark
                cycle_data.append(self._us_to_cycles(us))
            else:  # Space
                cycle_data.append(self._us_to_space_cycles(us))

        # Ensure even number of elements (mark/space pairs)
        if len(cycle_data) % 2 == 1:
            cycle_data.append(0)  # Add zero space at end

        # Start transmission
        self.sm.active(1)
        self.is_transmitting = True

        try:
            for cycles in cycle_data:
                self.sm.put(cycles)

            # Wait for completion
            total_us = sum(pulse_train)
            time.sleep_us(total_us + 1000)

        finally:
            self.sm.active(0)
            self.is_transmitting = False
            self.pin.value(0)

    def test_carrier(self, duration_ms: int = 100):
        """
        Test the carrier generation by outputting continuous carrier.

        Args:
            duration_ms: Duration in milliseconds
        """
        print(f"IR TX: Testing carrier for {duration_ms}ms")

        # Calculate cycles for continuous carrier
        carrier_cycles = self._us_to_cycles(duration_ms * 1000)

        self.sm.active(1)
        self.sm.put(carrier_cycles)  # Mark
        self.sm.put(0)  # No space

        time.sleep_ms(duration_ms + 10)

        self.sm.active(0)
        self.pin.value(0)
        print("IR TX: Carrier test complete")

    def test_command(self, command_code: int, repeats: int = 1, gap_ms: int = 57):
        """
        Test transmitting a command with repeats.

        Args:
            command_code: Command to send
            repeats: Number of times to repeat
            gap_ms: Gap between repeats in milliseconds
        """
        cmd_name = None
        for name in dir(IRCommand):
            if not name.startswith('_') and getattr(IRCommand, name) == command_code:
                cmd_name = name
                break

        print(f"IR TX: Testing {cmd_name or hex(command_code)} x{repeats}")

        for i in range(repeats):
            self.transmit_command(command_code)
            if i < repeats - 1:
                time.sleep_ms(gap_ms)

        print(f"IR TX: Test complete")


# =============================================================================
# Software-based IR Transmitter (Fallback)
# =============================================================================

class IRTransmitterSoftware:
    """
    Software-based IR transmitter using bit-banging.

    Less precise than PIO but works as a fallback.
    Uses tight timing loops for carrier generation.
    """

    def __init__(self, pin_num=PIN_IR_LED):
        self.pin = Pin(pin_num, Pin.OUT, value=0)
        self.carrier_half_period_us = 13  # ~38kHz (26us period)

    def _carrier_burst(self, duration_us: int):
        """Generate a carrier burst for the specified duration."""
        cycles = duration_us // 26
        for _ in range(cycles):
            self.pin.value(1)
            time.sleep_us(self.carrier_half_period_us)
            self.pin.value(0)
            time.sleep_us(self.carrier_half_period_us)

    def _space(self, duration_us: int):
        """Wait with IR LED off."""
        self.pin.value(0)
        time.sleep_us(duration_us)

    def transmit_command(self, command_code: int):
        """Transmit a command using software timing."""
        timings = protocol.encode_command(command_code)

        for mark_us, space_us in timings:
            self._carrier_burst(mark_us)
            if space_us > 0:
                self._space(space_us)

        self.pin.value(0)


# =============================================================================
# Module-level transmitter instance
# =============================================================================

# Create default transmitter
_transmitter = None


def get_transmitter(use_pio: bool = True) -> IRTransmitter:
    """Get or create the default IR transmitter instance."""
    global _transmitter
    if _transmitter is None:
        if use_pio:
            try:
                _transmitter = IRTransmitter()
            except Exception as e:
                print(f"PIO init failed, using software: {e}")
                _transmitter = IRTransmitterSoftware()
        else:
            _transmitter = IRTransmitterSoftware()
    return _transmitter


def send_command(command_code: int):
    """Convenience function to send a single command."""
    tx = get_transmitter()
    tx.transmit_command(command_code)


# =============================================================================
# Test code
# =============================================================================

if __name__ == "__main__":
    print("IR Transmitter Test")
    print("=" * 50)

    # Create transmitter
    tx = IRTransmitter()

    print("\nPress Ctrl+C to stop\n")

    # Test each command
    commands = [
        ("UP", IRCommand.UP),
        ("DOWN", IRCommand.DOWN),
        ("LEFT", IRCommand.LEFT),
        ("RIGHT", IRCommand.RIGHT),
        ("ZOOM_IN", IRCommand.ZOOM_IN),
        ("ZOOM_OUT", IRCommand.ZOOM_OUT),
    ]

    try:
        for name, cmd in commands:
            print(f"\nSending {name}...")
            tx.test_command(cmd, repeats=3, gap_ms=57)
            time.sleep(1)

    except KeyboardInterrupt:
        print("\nTest stopped")

    print("\nTest complete")
